### ISSUE TITLE
image size is too small

### ISSUE THREAD

**Issue by yxt132** [uvavision/chair-segments#1]
the size of the downloaded images is only 64 x 64. Do you have higher resolution images?

**Comment by leticiapinto** [comment]
Hi. I added some new changes to include 128x128 resolution.
You can run sh download_data.sh or download directly from https://www.cs.virginia.edu/~lp2rv/Datasets/Chair128.zip,  just make sure the unzipped Chair128 folder is in the data folder.

Also, to run this 128 resolution you need to include --resol=128.
For example:

python main.py --lr=1e-3 --arch=unet --optimizer=Adam --epochs=20 --resol=128

If you want to run 64x64 you don't have to include --resol=64, it's the default value.
